---
title: "Research"
---

Our research focuses on solving computational and mathematical problems
associated with improving election security, integrity, and trustworthiness.
This includes developing methodologies for risk-limiting post-election audits
for various election systems, and algorithms for analysing the properties of
elections, such as the margin of victory. 


## Background: Voting Schemes

Our research primarily considers election systems in which voters rank
candidates according to their preferences, commonly referred to as preferential
or ranked-choice elections. 

### Instant Runoff Voting (IRV)

Instant Runoff Voting (IRV) is a preferential, or ranked-choice, voting scheme. 
Voters cast a ballot in which they *rank* the
set of candidates from most to least preferred. Depending on the jurisdiction,
each vote may express a total, or partial, order over the set of candidates.
Each ballot represents a single vote. 

An IRV election is tabulated in rounds. In the first round, each candidate has a
tally pile consisting of all the ballots on which they have been ranked first
(highest). The number of ballots in this pile (the number of votes) represents 
their *first preference tally*. While no candidate
has the majority of votes, the candidate with the smallest tally is
*eliminated*. All ballots in their tally pile are then given to the next most
preferred eligible candidate on the ballot. A candidate is eligible to receive
new ballots in their pile if they are still standing (not yet eliminated).
Ballots with no further elibigle candidates in their ranking become *exhausted*.
When one candidate has the majority of votes, they are declared the winner.
Alternatively, we can continue to eliminated the candidate with the smallest
tally until one candidate remains. This last remaining candidate is declared the
winner.
 
IRV is used in Australia to elect candidates to our lower houses of State and
Federal Parliaments. It is also increasingly being used in the [United
States](https://www.rcvresources.org/where-is-rcv-used), with a different
moniker -- Ranked Choice Voting (RCV). 

### Single Transferable Vote (STV)

The Single Transferable Vote (STV) is a multi-winner preferential and
proportional voting system. It is used in Australia to elect candidates to the 
upper houses of our State and Federal Parliaments, and at the local council
level when electing multiple councillors for a given district. STV is also used
at the local council level in Scotland and the United States. 

More complex than IRV, the tabulation of an STV election proceeds in rounds of
candidate election and elimination. A candidate is elected in two circumstances:
when their tally reaches or exceeds a threshold known as the *quota*; or when
they remain standing at a point where the number of candidates left equals the
number of seats left to be filled. The election's quota can be computed in
different ways, with the [Droop quota](https://en.wikipedia.org/wiki/Droop_quota) commonly used. If no candidate has a quota's worth of votes
in their tally at the start of a round, the candidate with the smallest tally is
eliminated, with the ballots in their tally reassigned to the tally piles of
later preferences on the ballot. 

As per IRV, candidates in an STV election are initially given all ballots on
which they have been ranked first (most preferred). This forms their first
preference tally, with all ballots starting with a value of 1 vote. A key
complexity of STV is that ballots change in value over the course of tabulation. 

When a candidate is eliminated, each ballot in their tally pile is given to the next most preferred
eligible candidate on the ballot *at its current value*. A candidate is eligible
to receive votes if and only if they have not yet been seated or eliminated, and they did
not already have a quota's worth of votes at the start of the round. When a
candidate is elected to a seat, each of their ballots is given to the next most
preferred eligible candidates on the ballot *at a reduced value*. How this
reduced value is computed varies across different implementations of STV. 

STV tabulation proceeds in rounds of candidate election and elimination until
either all seats have been filled, or the number of continuing candidates (those
that have not yet been eliminated or elected) equals the number of seats left to
be filled.

## Risk Limiting Audits

Risk limiting audits (RLAs) are a post-election activity, performed to provide a certain level of confidence
in the correctness of the reported outcome, or to correct a wrong outcome by manual recount. These
audits involve randomly sampling paper ballots that have been cast by voters. After collecting and
analysing such a sample, statistical computations are performed to ascertain a current level of risk. A
Risk Limiting Audit guarantees a *risk limit*: the maximum probability that it will mistakenly confirm a
reported outcome that was in fact wrong. The audit proceeds by sampling ballots until this risk falls
below an acceptable level, or election administrators determine that a full manual count is required.

### RAIRE

**R**isk limiting **A**udits for **IR**V **E**lections (RAIRE) allows election administrators to conduct Risk Limiting
Audits (RLAs) for Instant Runoff Voting (IRV) elections. This work introduced
the concept of an *assertion-based* audit. An assertion is a mathematical
statement, comparing two tallies in a specific context. These two tallies may be
the tallies of two candidates in the context where we assume a certain subset of
candidates are still standing. Given digitised preferences for the ballots cast
in an IRV election, RAIRE identifies a set of assertions that, if verified in an
RLA, imply that the announced (reported) winner won. RAIRE uses a
branch-and-bound algorithm to find a set of assertions that require auditors to
sample the least number of ballots. 

RAIRE has been piloted in a number of
US-based IRV elections: the 2019 San Francisco District Attorney contest; three
2020 Democratic Presidential Primaries; and a Mayoral Contest in Boulder,
Colorado, in November 2023. 

From 2025, RAIRE will be used to audit IRV elections
taking place in Colorado, United States, through a project with the Australian
not-for-profit [Democracy
Developers](https://www.democracydevelopers.org.au/about-us/). For an accessible
introduction to RLAs with RAIRE, see the [Guide to RAIRE Part
1](https://dx.doi.org/10.13140/RG.2.2.33366.56644) and the [Guide to
Raire Part 2](https://dx.doi.org/10.13140/RG.2.2.16589.35045). 

### AWAIRE

### RLAs for STV Elections

Developing risk-limiting audits for STV elections is challenging, given the high
complexity of the STV counting algorithm and the variation in how it is
implemented across jurisdictions. We have made progress in developing RLAs for
some classes of STV elections.

- 2 seat STV elections where the first winner is elected in the first round. We
  have published two papers to date on this case, with the more recent paper
presenting an improved method resulting in audits that sample less ballots.
    - [A First Approach to Risk-Limiting Audits for
Single Transferable Vote Elections](https://arxiv.org/pdf/2112.09921)
    - [RLAs for 2-Seat STV Elections: Revisited](https://arxiv.org/pdf/2402.03707)


- STV elections of 3 seats or more, restricted to the cases where the first
  winner is elected in the first round.
    - [3+ Seat Risk-Limiting Audits for Single Transferable Vote
      Elections](https://arxiv.org/abs/2503.14803)

### Mismatch Audits

## Margin Computation

Knowing how close an election was provides useful information when assessing
whether certain known errors could have influenced the outcome. The margin of
victory of an election can be defined as the smallest number of ballots that we
would have to manipulate (alter) in order to change who won. We have developed
methods to compute margins of victory for [IRV
elections](https://ebooks.iospress.nl/doi/10.3233/978-1-61499-672-9-480) and for
computing lower bounds on the margin of victory for [STV
elections](https://pubsonline.informs.org/doi/abs/10.1287/ijoc.2018.0853).

The computation of tight lower bounds on the margin for STV elections is still
an open problem, particularly for large STV elections with many seats and over a
hundred candidates. Margin computation under more flexible definitions of the
margin, where manipulations can include modidification, addition, and removal of
ballots, is another open challenge. 


## Security, Accuracy and Privacy 

